version: 0.1.{build}

branches:
  only:
    - master

image: Visual Studio 2017
platform:
  - x64

cache:
  - node_modules
  - '%APPDATA%\npm-cache'
  - '%USERPROFILE%\.electron'
  - '%USERPROFILE%\AppData\Local\Yarn\cache'

init:
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node 8 x64
  # - choco install yarn --ignore-dependencies
  - ps: Write-Host "Installing Yarn 1.3.2..."
  - ps: (New-Object Net.WebClient).DownloadFile('https://github.com/yarnpkg/yarn/releases/download/v1.3.2/yarn-1.3.2.msi', "$env:temp\yarn-1.3.2.msi")
  - cmd /c start /wait msiexec.exe /i $env:temp\yarn-1.3.2.msi /quiet
  - git reset --hard HEAD
  - yarn
  - node --version

build_script:
  - yarn build

test: off
